[package]
name = "garfsay"
version = "0.1.0"
authors = ["Ian Schwartz <ian@schwartz.world>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
